
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/10.0.1.67:40001,10.0.1.67:40002,10.0.1.67:40003 --bind_ip_all --port 27017
    ports:
      - 60000:27017
